# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "tfstate"
    key                  = "terragrunt.tfstate"
    resource_group_name  = "practice-tfstate"
    storage_account_name = "practicetfstatedame"
    subscription_id      = "d1ac2c8c-6294-46bc-ae8c-4188669ccbbc"
    tenant_id            = "a2091806-2bd5-424d-a1ec-8b44a0373dd1"
  }
}
